// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ObjectFinder.proto
#ifndef GRPC_ObjectFinder_2eproto__INCLUDED
#define GRPC_ObjectFinder_2eproto__INCLUDED

#include "ObjectFinder.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ObjectFinder {

class ObjectFinderServiceGRPC final {
 public:
  static constexpr char const* service_full_name() {
    return "ObjectFinder.ObjectFinderServiceGRPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::ObjectFinder::ImageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ObjectFinder::ImageResponse>> AsyncSelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ObjectFinder::ImageResponse>>(AsyncSelectObjectsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ObjectFinder::ImageResponse>> PrepareAsyncSelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ObjectFinder::ImageResponse>>(PrepareAsyncSelectObjectsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ObjectFinder::ImageResponse>* AsyncSelectObjectsRaw(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ObjectFinder::ImageResponse>* PrepareAsyncSelectObjectsRaw(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::ObjectFinder::ImageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>> AsyncSelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>>(AsyncSelectObjectsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>> PrepareAsyncSelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>>(PrepareAsyncSelectObjectsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response, std::function<void(::grpc::Status)>) override;
      void SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>* AsyncSelectObjectsRaw(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>* PrepareAsyncSelectObjectsRaw(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SelectObjects_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SelectObjects(::grpc::ServerContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SelectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SelectObjects() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SelectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectObjects(::grpc::ServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSelectObjects(::grpc::ServerContext* context, ::ObjectFinder::ImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::ObjectFinder::ImageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SelectObjects<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SelectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SelectObjects() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response) { return this->SelectObjects(context, request, response); }));}
    void SetMessageAllocatorFor_SelectObjects(
        ::grpc::MessageAllocator< ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SelectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectObjects(::grpc::ServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SelectObjects(
      ::grpc::CallbackServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SelectObjects<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SelectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SelectObjects() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SelectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectObjects(::grpc::ServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SelectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SelectObjects() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SelectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectObjects(::grpc::ServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSelectObjects(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SelectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SelectObjects() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SelectObjects(context, request, response); }));
    }
    ~WithRawCallbackMethod_SelectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SelectObjects(::grpc::ServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SelectObjects(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SelectObjects : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SelectObjects() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse>* streamer) {
                       return this->StreamedSelectObjects(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SelectObjects() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SelectObjects(::grpc::ServerContext* /*context*/, const ::ObjectFinder::ImageRequest* /*request*/, ::ObjectFinder::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSelectObjects(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ObjectFinder::ImageRequest,::ObjectFinder::ImageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SelectObjects<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SelectObjects<Service > StreamedService;
};

}  // namespace ObjectFinder


#endif  // GRPC_ObjectFinder_2eproto__INCLUDED
