// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ObjectFinder.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ObjectFinder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ObjectFinder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ObjectFinder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ObjectFinder_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ObjectFinder_2eproto;
namespace ObjectFinder {
class ImageRequest;
struct ImageRequestDefaultTypeInternal;
extern ImageRequestDefaultTypeInternal _ImageRequest_default_instance_;
class ImageResponse;
struct ImageResponseDefaultTypeInternal;
extern ImageResponseDefaultTypeInternal _ImageResponse_default_instance_;
class PolygonData;
struct PolygonDataDefaultTypeInternal;
extern PolygonDataDefaultTypeInternal _PolygonData_default_instance_;
}  // namespace ObjectFinder
PROTOBUF_NAMESPACE_OPEN
template<> ::ObjectFinder::ImageRequest* Arena::CreateMaybeMessage<::ObjectFinder::ImageRequest>(Arena*);
template<> ::ObjectFinder::ImageResponse* Arena::CreateMaybeMessage<::ObjectFinder::ImageResponse>(Arena*);
template<> ::ObjectFinder::PolygonData* Arena::CreateMaybeMessage<::ObjectFinder::PolygonData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ObjectFinder {

enum PolygonType : int {
  INCLUDE = 0,
  EXCLUDE = 1,
  PolygonType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PolygonType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PolygonType_IsValid(int value);
constexpr PolygonType PolygonType_MIN = INCLUDE;
constexpr PolygonType PolygonType_MAX = EXCLUDE;
constexpr int PolygonType_ARRAYSIZE = PolygonType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PolygonType_descriptor();
template<typename T>
inline const std::string& PolygonType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PolygonType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PolygonType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PolygonType_descriptor(), enum_t_value);
}
inline bool PolygonType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PolygonType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PolygonType>(
    PolygonType_descriptor(), name, value);
}
// ===================================================================

class PolygonData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ObjectFinder.PolygonData) */ {
 public:
  inline PolygonData() : PolygonData(nullptr) {}
  ~PolygonData() override;
  explicit PROTOBUF_CONSTEXPR PolygonData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolygonData(const PolygonData& from);
  PolygonData(PolygonData&& from) noexcept
    : PolygonData() {
    *this = ::std::move(from);
  }

  inline PolygonData& operator=(const PolygonData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolygonData& operator=(PolygonData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PolygonData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PolygonData* internal_default_instance() {
    return reinterpret_cast<const PolygonData*>(
               &_PolygonData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PolygonData& a, PolygonData& b) {
    a.Swap(&b);
  }
  inline void Swap(PolygonData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolygonData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolygonData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolygonData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PolygonData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PolygonData& from) {
    PolygonData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolygonData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ObjectFinder.PolygonData";
  }
  protected:
  explicit PolygonData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCoordsFieldNumber = 1,
    kObjclassesFieldNumber = 5,
    kTypeFieldNumber = 2,
    kThresholdFieldNumber = 3,
    kPriorityFieldNumber = 4,
  };
  // repeated float coords = 1;
  int coords_size() const;
  private:
  int _internal_coords_size() const;
  public:
  void clear_coords();
  private:
  float _internal_coords(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_coords() const;
  void _internal_add_coords(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_coords();
  public:
  float coords(int index) const;
  void set_coords(int index, float value);
  void add_coords(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      coords() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_coords();

  // repeated int32 objclasses = 5;
  int objclasses_size() const;
  private:
  int _internal_objclasses_size() const;
  public:
  void clear_objclasses();
  private:
  int32_t _internal_objclasses(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_objclasses() const;
  void _internal_add_objclasses(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_objclasses();
  public:
  int32_t objclasses(int index) const;
  void set_objclasses(int index, int32_t value);
  void add_objclasses(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      objclasses() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_objclasses();

  // .ObjectFinder.PolygonType type = 2;
  void clear_type();
  ::ObjectFinder::PolygonType type() const;
  void set_type(::ObjectFinder::PolygonType value);
  private:
  ::ObjectFinder::PolygonType _internal_type() const;
  void _internal_set_type(::ObjectFinder::PolygonType value);
  public:

  // float threshold = 3;
  void clear_threshold();
  float threshold() const;
  void set_threshold(float value);
  private:
  float _internal_threshold() const;
  void _internal_set_threshold(float value);
  public:

  // int32 priority = 4;
  void clear_priority();
  int32_t priority() const;
  void set_priority(int32_t value);
  private:
  int32_t _internal_priority() const;
  void _internal_set_priority(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ObjectFinder.PolygonData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > coords_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > objclasses_;
    mutable std::atomic<int> _objclasses_cached_byte_size_;
    int type_;
    float threshold_;
    int32_t priority_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ObjectFinder_2eproto;
};
// -------------------------------------------------------------------

class ImageRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ObjectFinder.ImageRequest) */ {
 public:
  inline ImageRequest() : ImageRequest(nullptr) {}
  ~ImageRequest() override;
  explicit PROTOBUF_CONSTEXPR ImageRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImageRequest(const ImageRequest& from);
  ImageRequest(ImageRequest&& from) noexcept
    : ImageRequest() {
    *this = ::std::move(from);
  }

  inline ImageRequest& operator=(const ImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageRequest& operator=(ImageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageRequest* internal_default_instance() {
    return reinterpret_cast<const ImageRequest*>(
               &_ImageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ImageRequest& a, ImageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImageRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ImageRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ImageRequest& from) {
    ImageRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ObjectFinder.ImageRequest";
  }
  protected:
  explicit ImageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPolygonsFieldNumber = 2,
    kImageFieldNumber = 1,
  };
  // repeated .ObjectFinder.PolygonData polygons = 2;
  int polygons_size() const;
  private:
  int _internal_polygons_size() const;
  public:
  void clear_polygons();
  ::ObjectFinder::PolygonData* mutable_polygons(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ObjectFinder::PolygonData >*
      mutable_polygons();
  private:
  const ::ObjectFinder::PolygonData& _internal_polygons(int index) const;
  ::ObjectFinder::PolygonData* _internal_add_polygons();
  public:
  const ::ObjectFinder::PolygonData& polygons(int index) const;
  ::ObjectFinder::PolygonData* add_polygons();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ObjectFinder::PolygonData >&
      polygons() const;

  // bytes image = 1;
  void clear_image();
  const std::string& image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image();
  PROTOBUF_NODISCARD std::string* release_image();
  void set_allocated_image(std::string* image);
  private:
  const std::string& _internal_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image(const std::string& value);
  std::string* _internal_mutable_image();
  public:

  // @@protoc_insertion_point(class_scope:ObjectFinder.ImageRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ObjectFinder::PolygonData > polygons_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ObjectFinder_2eproto;
};
// -------------------------------------------------------------------

class ImageResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ObjectFinder.ImageResponse) */ {
 public:
  inline ImageResponse() : ImageResponse(nullptr) {}
  ~ImageResponse() override;
  explicit PROTOBUF_CONSTEXPR ImageResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImageResponse(const ImageResponse& from);
  ImageResponse(ImageResponse&& from) noexcept
    : ImageResponse() {
    *this = ::std::move(from);
  }

  inline ImageResponse& operator=(const ImageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageResponse& operator=(ImageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageResponse* internal_default_instance() {
    return reinterpret_cast<const ImageResponse*>(
               &_ImageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ImageResponse& a, ImageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImageResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ImageResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ImageResponse& from) {
    ImageResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ObjectFinder.ImageResponse";
  }
  protected:
  explicit ImageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageFieldNumber = 1,
  };
  // bytes image = 1;
  void clear_image();
  const std::string& image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image();
  PROTOBUF_NODISCARD std::string* release_image();
  void set_allocated_image(std::string* image);
  private:
  const std::string& _internal_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image(const std::string& value);
  std::string* _internal_mutable_image();
  public:

  // @@protoc_insertion_point(class_scope:ObjectFinder.ImageResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ObjectFinder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PolygonData

// repeated float coords = 1;
inline int PolygonData::_internal_coords_size() const {
  return _impl_.coords_.size();
}
inline int PolygonData::coords_size() const {
  return _internal_coords_size();
}
inline void PolygonData::clear_coords() {
  _impl_.coords_.Clear();
}
inline float PolygonData::_internal_coords(int index) const {
  return _impl_.coords_.Get(index);
}
inline float PolygonData::coords(int index) const {
  // @@protoc_insertion_point(field_get:ObjectFinder.PolygonData.coords)
  return _internal_coords(index);
}
inline void PolygonData::set_coords(int index, float value) {
  _impl_.coords_.Set(index, value);
  // @@protoc_insertion_point(field_set:ObjectFinder.PolygonData.coords)
}
inline void PolygonData::_internal_add_coords(float value) {
  _impl_.coords_.Add(value);
}
inline void PolygonData::add_coords(float value) {
  _internal_add_coords(value);
  // @@protoc_insertion_point(field_add:ObjectFinder.PolygonData.coords)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PolygonData::_internal_coords() const {
  return _impl_.coords_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PolygonData::coords() const {
  // @@protoc_insertion_point(field_list:ObjectFinder.PolygonData.coords)
  return _internal_coords();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PolygonData::_internal_mutable_coords() {
  return &_impl_.coords_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PolygonData::mutable_coords() {
  // @@protoc_insertion_point(field_mutable_list:ObjectFinder.PolygonData.coords)
  return _internal_mutable_coords();
}

// .ObjectFinder.PolygonType type = 2;
inline void PolygonData::clear_type() {
  _impl_.type_ = 0;
}
inline ::ObjectFinder::PolygonType PolygonData::_internal_type() const {
  return static_cast< ::ObjectFinder::PolygonType >(_impl_.type_);
}
inline ::ObjectFinder::PolygonType PolygonData::type() const {
  // @@protoc_insertion_point(field_get:ObjectFinder.PolygonData.type)
  return _internal_type();
}
inline void PolygonData::_internal_set_type(::ObjectFinder::PolygonType value) {
  
  _impl_.type_ = value;
}
inline void PolygonData::set_type(::ObjectFinder::PolygonType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ObjectFinder.PolygonData.type)
}

// float threshold = 3;
inline void PolygonData::clear_threshold() {
  _impl_.threshold_ = 0;
}
inline float PolygonData::_internal_threshold() const {
  return _impl_.threshold_;
}
inline float PolygonData::threshold() const {
  // @@protoc_insertion_point(field_get:ObjectFinder.PolygonData.threshold)
  return _internal_threshold();
}
inline void PolygonData::_internal_set_threshold(float value) {
  
  _impl_.threshold_ = value;
}
inline void PolygonData::set_threshold(float value) {
  _internal_set_threshold(value);
  // @@protoc_insertion_point(field_set:ObjectFinder.PolygonData.threshold)
}

// int32 priority = 4;
inline void PolygonData::clear_priority() {
  _impl_.priority_ = 0;
}
inline int32_t PolygonData::_internal_priority() const {
  return _impl_.priority_;
}
inline int32_t PolygonData::priority() const {
  // @@protoc_insertion_point(field_get:ObjectFinder.PolygonData.priority)
  return _internal_priority();
}
inline void PolygonData::_internal_set_priority(int32_t value) {
  
  _impl_.priority_ = value;
}
inline void PolygonData::set_priority(int32_t value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:ObjectFinder.PolygonData.priority)
}

// repeated int32 objclasses = 5;
inline int PolygonData::_internal_objclasses_size() const {
  return _impl_.objclasses_.size();
}
inline int PolygonData::objclasses_size() const {
  return _internal_objclasses_size();
}
inline void PolygonData::clear_objclasses() {
  _impl_.objclasses_.Clear();
}
inline int32_t PolygonData::_internal_objclasses(int index) const {
  return _impl_.objclasses_.Get(index);
}
inline int32_t PolygonData::objclasses(int index) const {
  // @@protoc_insertion_point(field_get:ObjectFinder.PolygonData.objclasses)
  return _internal_objclasses(index);
}
inline void PolygonData::set_objclasses(int index, int32_t value) {
  _impl_.objclasses_.Set(index, value);
  // @@protoc_insertion_point(field_set:ObjectFinder.PolygonData.objclasses)
}
inline void PolygonData::_internal_add_objclasses(int32_t value) {
  _impl_.objclasses_.Add(value);
}
inline void PolygonData::add_objclasses(int32_t value) {
  _internal_add_objclasses(value);
  // @@protoc_insertion_point(field_add:ObjectFinder.PolygonData.objclasses)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PolygonData::_internal_objclasses() const {
  return _impl_.objclasses_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PolygonData::objclasses() const {
  // @@protoc_insertion_point(field_list:ObjectFinder.PolygonData.objclasses)
  return _internal_objclasses();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PolygonData::_internal_mutable_objclasses() {
  return &_impl_.objclasses_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PolygonData::mutable_objclasses() {
  // @@protoc_insertion_point(field_mutable_list:ObjectFinder.PolygonData.objclasses)
  return _internal_mutable_objclasses();
}

// -------------------------------------------------------------------

// ImageRequest

// bytes image = 1;
inline void ImageRequest::clear_image() {
  _impl_.image_.ClearToEmpty();
}
inline const std::string& ImageRequest::image() const {
  // @@protoc_insertion_point(field_get:ObjectFinder.ImageRequest.image)
  return _internal_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ImageRequest::set_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ObjectFinder.ImageRequest.image)
}
inline std::string* ImageRequest::mutable_image() {
  std::string* _s = _internal_mutable_image();
  // @@protoc_insertion_point(field_mutable:ObjectFinder.ImageRequest.image)
  return _s;
}
inline const std::string& ImageRequest::_internal_image() const {
  return _impl_.image_.Get();
}
inline void ImageRequest::_internal_set_image(const std::string& value) {
  
  _impl_.image_.Set(value, GetArenaForAllocation());
}
inline std::string* ImageRequest::_internal_mutable_image() {
  
  return _impl_.image_.Mutable(GetArenaForAllocation());
}
inline std::string* ImageRequest::release_image() {
  // @@protoc_insertion_point(field_release:ObjectFinder.ImageRequest.image)
  return _impl_.image_.Release();
}
inline void ImageRequest::set_allocated_image(std::string* image) {
  if (image != nullptr) {
    
  } else {
    
  }
  _impl_.image_.SetAllocated(image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_.IsDefault()) {
    _impl_.image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ObjectFinder.ImageRequest.image)
}

// repeated .ObjectFinder.PolygonData polygons = 2;
inline int ImageRequest::_internal_polygons_size() const {
  return _impl_.polygons_.size();
}
inline int ImageRequest::polygons_size() const {
  return _internal_polygons_size();
}
inline void ImageRequest::clear_polygons() {
  _impl_.polygons_.Clear();
}
inline ::ObjectFinder::PolygonData* ImageRequest::mutable_polygons(int index) {
  // @@protoc_insertion_point(field_mutable:ObjectFinder.ImageRequest.polygons)
  return _impl_.polygons_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ObjectFinder::PolygonData >*
ImageRequest::mutable_polygons() {
  // @@protoc_insertion_point(field_mutable_list:ObjectFinder.ImageRequest.polygons)
  return &_impl_.polygons_;
}
inline const ::ObjectFinder::PolygonData& ImageRequest::_internal_polygons(int index) const {
  return _impl_.polygons_.Get(index);
}
inline const ::ObjectFinder::PolygonData& ImageRequest::polygons(int index) const {
  // @@protoc_insertion_point(field_get:ObjectFinder.ImageRequest.polygons)
  return _internal_polygons(index);
}
inline ::ObjectFinder::PolygonData* ImageRequest::_internal_add_polygons() {
  return _impl_.polygons_.Add();
}
inline ::ObjectFinder::PolygonData* ImageRequest::add_polygons() {
  ::ObjectFinder::PolygonData* _add = _internal_add_polygons();
  // @@protoc_insertion_point(field_add:ObjectFinder.ImageRequest.polygons)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ObjectFinder::PolygonData >&
ImageRequest::polygons() const {
  // @@protoc_insertion_point(field_list:ObjectFinder.ImageRequest.polygons)
  return _impl_.polygons_;
}

// -------------------------------------------------------------------

// ImageResponse

// bytes image = 1;
inline void ImageResponse::clear_image() {
  _impl_.image_.ClearToEmpty();
}
inline const std::string& ImageResponse::image() const {
  // @@protoc_insertion_point(field_get:ObjectFinder.ImageResponse.image)
  return _internal_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ImageResponse::set_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ObjectFinder.ImageResponse.image)
}
inline std::string* ImageResponse::mutable_image() {
  std::string* _s = _internal_mutable_image();
  // @@protoc_insertion_point(field_mutable:ObjectFinder.ImageResponse.image)
  return _s;
}
inline const std::string& ImageResponse::_internal_image() const {
  return _impl_.image_.Get();
}
inline void ImageResponse::_internal_set_image(const std::string& value) {
  
  _impl_.image_.Set(value, GetArenaForAllocation());
}
inline std::string* ImageResponse::_internal_mutable_image() {
  
  return _impl_.image_.Mutable(GetArenaForAllocation());
}
inline std::string* ImageResponse::release_image() {
  // @@protoc_insertion_point(field_release:ObjectFinder.ImageResponse.image)
  return _impl_.image_.Release();
}
inline void ImageResponse::set_allocated_image(std::string* image) {
  if (image != nullptr) {
    
  } else {
    
  }
  _impl_.image_.SetAllocated(image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_.IsDefault()) {
    _impl_.image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ObjectFinder.ImageResponse.image)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ObjectFinder

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ObjectFinder::PolygonType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ObjectFinder::PolygonType>() {
  return ::ObjectFinder::PolygonType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ObjectFinder_2eproto
