// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ObjectFinder.proto

#include "ObjectFinder.pb.h"
#include "ObjectFinder.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ObjectFinder {

static const char* ObjectFinderServiceGRPC_method_names[] = {
  "/ObjectFinder.ObjectFinderServiceGRPC/SelectObjects",
};

std::unique_ptr< ObjectFinderServiceGRPC::Stub> ObjectFinderServiceGRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ObjectFinderServiceGRPC::Stub> stub(new ObjectFinderServiceGRPC::Stub(channel, options));
  return stub;
}

ObjectFinderServiceGRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SelectObjects_(ObjectFinderServiceGRPC_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ObjectFinderServiceGRPC::Stub::SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::ObjectFinder::ImageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SelectObjects_, context, request, response);
}

void ObjectFinderServiceGRPC::Stub::async::SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SelectObjects_, context, request, response, std::move(f));
}

void ObjectFinderServiceGRPC::Stub::async::SelectObjects(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SelectObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>* ObjectFinderServiceGRPC::Stub::PrepareAsyncSelectObjectsRaw(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ObjectFinder::ImageResponse, ::ObjectFinder::ImageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SelectObjects_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ObjectFinder::ImageResponse>* ObjectFinderServiceGRPC::Stub::AsyncSelectObjectsRaw(::grpc::ClientContext* context, const ::ObjectFinder::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSelectObjectsRaw(context, request, cq);
  result->StartCall();
  return result;
}

ObjectFinderServiceGRPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ObjectFinderServiceGRPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ObjectFinderServiceGRPC::Service, ::ObjectFinder::ImageRequest, ::ObjectFinder::ImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ObjectFinderServiceGRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ObjectFinder::ImageRequest* req,
             ::ObjectFinder::ImageResponse* resp) {
               return service->SelectObjects(ctx, req, resp);
             }, this)));
}

ObjectFinderServiceGRPC::Service::~Service() {
}

::grpc::Status ObjectFinderServiceGRPC::Service::SelectObjects(::grpc::ServerContext* context, const ::ObjectFinder::ImageRequest* request, ::ObjectFinder::ImageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ObjectFinder

